### ISSUE TITLE
Initial thoughts ...

### ISSUE THREAD

**Issue by TiddlyTweeter** [Arlen22/TiddlyWiki-DocsWiki#1]
This is a good idea. But to move towards some kind of docs I'm not yet clear what I could contribute ....

My thought is to focus on three things ...

1. Be for beginner single file TW use?
2. Use a Q & A format so that individual contributors can contribute within areas of competence that can be created and updated easily?
3. Rather than try to be wholely original writing, try to bring together work that has already been done?

My initial thoughts. I'm not getting into this unless I have sense there is some kind of "path" ahead.

But other people have individually made wiki that give lists of beginner concerns they work on. Maybe they should be looked to for a clearer idea?

Anyway, for now, I'll just wait to see comments on my thoughts (in no way binding!)

**Comment by Arlen22** [comment]
The path ahead I see for this is collaboration. This wiki is created to allow everyone to edit the same page. So I don't think we should necessarily aim to create another missing manual.

**Comment by TiddlyTweeter** [comment]
@Arlen22 I agree. Its better to be user interest/competence driven. 

If I don't enjoy what I'm doing I will quickly get fed up. For myself I like to have an area of competence I can write about. This is partly why I think a Q&A format might be worth considering?

**Comment by Arlen22** [comment]
You're welcome to contribute whatever you like. It's up to you. The wiki
should be flexible enough to accommodate many writing styles.

**Comment by TiddlyTweeter** [comment]
@Arlen22 understood. But I won't do it alone.

**Comment by Arlen22** [comment]
That's fine, of course. I've mentioned this several places so I'm just waiting to see who all comes. You're welcome to bring a team if you like, but if it's easier for you to do more of a solo project and host it elsewhere, then by all means go for it. I just made this for a more central place that everyone can contribute to.

**Comment by TiddlyTweeter** [comment]
If a few more people sign up & comment I'll do it. I NEVER write docs without a framework. There is no point.

**Comment by Arlen22** [comment]
I think I know what you're referring to. Yeah, that's fine, no problem.
